#!/usr/bin/env python
import os
import arapi

PORT = 8091
HOST = '0.0.0.0'

os.environ['ARAPI_CONFIG'] = './arapi/conf/arapi_dev.cfg'
os.environ['ARAPI_DEBUG'] = 'Yeah'

if __name__ == '__main__':
    arapi.GetMainApp().run(port=PORT, host=HOST, debug=True)
